void flags(int *L,int *,string *,string *,string *,int ,char **);
int a(int ,double ,int);
int h(int ,int ,int );
int modulo_(int , int );
void h_calc(Dianisma *,int ,int ,Alfa ,long long ,int );
void gx_calc(Dianisma *,int ,int );
int MOD_power(long long ,  int , int );
void hashing(Dianisma *,int ,int );
int Big_mod(long long , int );
int manhatan_dist(Dianisma *,Dianisma *,int );
int get_W(string );
