void flags(double *,int *,int *,string *,string *,string *,int ,char **);
int a(double ,double ,int);
void removeCharsFromString( string &, char* );
int h(int ,int ,int );
int modulo_(int , int );
void h_calc(Dianisma *,int ,int ,Alfa ,long long ,int );
void gx_calc(Dianisma *,int ,int );
int MOD_power(long long ,  int , int );
void hashing(Dianisma *,int ,int );
int Big_mod(long long , int );
int manhatan_dist(Dianisma *,Dianisma *,int );
int get_W(string );
double DTW(Curves& ,Curves&);
double Euclidean_dist(vector<double> ,vector<double> );
void find_paths(int , int ,vector<vector<point>> *);
